# Generated by Django 5.2.17 on 2026-09-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_remove_lead_uniq_owner_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadactivity',
            name='type',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('status_changed', 'Status changed'), ('assigned', 'Assigned')], max_length=20),
        ),
    ]
